language: node_js
node_js:
  - '6'
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_46a623e08d1b_key -iv $encrypted_46a623e08d1b_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "Karl Li"
  - git config --global user.email killtw@gmail.com
install:
  - npm install -g hexo-cli
  - npm install
script:
  - hexo deploy
